require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DictionariesController do

  # This should return the minimal set of attributes required to create a valid
  # Dictionary. As you add validations to Dictionary, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DictionariesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dictionaries as @dictionaries" do
      dictionary = Dictionary.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dictionaries).should eq([dictionary])
    end
  end

  describe "GET show" do
    it "assigns the requested dictionary as @dictionary" do
      dictionary = Dictionary.create! valid_attributes
      get :show, {:id => dictionary.to_param}, valid_session
      assigns(:dictionary).should eq(dictionary)
    end
  end

  describe "GET new" do
    it "assigns a new dictionary as @dictionary" do
      get :new, {}, valid_session
      assigns(:dictionary).should be_a_new(Dictionary)
    end
  end

  describe "GET edit" do
    it "assigns the requested dictionary as @dictionary" do
      dictionary = Dictionary.create! valid_attributes
      get :edit, {:id => dictionary.to_param}, valid_session
      assigns(:dictionary).should eq(dictionary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dictionary" do
        expect {
          post :create, {:dictionary => valid_attributes}, valid_session
        }.to change(Dictionary, :count).by(1)
      end

      it "assigns a newly created dictionary as @dictionary" do
        post :create, {:dictionary => valid_attributes}, valid_session
        assigns(:dictionary).should be_a(Dictionary)
        assigns(:dictionary).should be_persisted
      end

      it "redirects to the created dictionary" do
        post :create, {:dictionary => valid_attributes}, valid_session
        response.should redirect_to(Dictionary.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dictionary as @dictionary" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionary.any_instance.stub(:save).and_return(false)
        post :create, {:dictionary => {}}, valid_session
        assigns(:dictionary).should be_a_new(Dictionary)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionary.any_instance.stub(:save).and_return(false)
        post :create, {:dictionary => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dictionary" do
        dictionary = Dictionary.create! valid_attributes
        # Assuming there are no other dictionaries in the database, this
        # specifies that the Dictionary created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dictionary.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dictionary.to_param, :dictionary => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dictionary as @dictionary" do
        dictionary = Dictionary.create! valid_attributes
        put :update, {:id => dictionary.to_param, :dictionary => valid_attributes}, valid_session
        assigns(:dictionary).should eq(dictionary)
      end

      it "redirects to the dictionary" do
        dictionary = Dictionary.create! valid_attributes
        put :update, {:id => dictionary.to_param, :dictionary => valid_attributes}, valid_session
        response.should redirect_to(dictionary)
      end
    end

    describe "with invalid params" do
      it "assigns the dictionary as @dictionary" do
        dictionary = Dictionary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionary.any_instance.stub(:save).and_return(false)
        put :update, {:id => dictionary.to_param, :dictionary => {}}, valid_session
        assigns(:dictionary).should eq(dictionary)
      end

      it "re-renders the 'edit' template" do
        dictionary = Dictionary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dictionary.any_instance.stub(:save).and_return(false)
        put :update, {:id => dictionary.to_param, :dictionary => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dictionary" do
      dictionary = Dictionary.create! valid_attributes
      expect {
        delete :destroy, {:id => dictionary.to_param}, valid_session
      }.to change(Dictionary, :count).by(-1)
    end

    it "redirects to the dictionaries list" do
      dictionary = Dictionary.create! valid_attributes
      delete :destroy, {:id => dictionary.to_param}, valid_session
      response.should redirect_to(dictionaries_url)
    end
  end

end
